" ============================================================
" Clean Vim Config - Zain Orwa
" macOS / Mac M1
" ============================================================

set nocompatible
syntax on
filetype plugin indent on

" ---------- Basic ----------
set encoding=utf-8
set mouse=a
set backspace=indent,eol,start
set hidden
set updatetime=300
set shortmess+=c
set signcolumn=yes
set clipboard=unnamed
set termguicolors
set nolist

" ---------- UI ----------
set number
set relativenumber
set cursorline
set ruler
set showcmd
set laststatus=2
set noshowmode

" ---------- Tabs / Indentation ----------
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent

" ---------- Search ----------
set ignorecase
set smartcase
set incsearch
set hlsearch

" ---------- Splits ----------
set splitbelow
set splitright

" ---------- Undo / Backup ----------
set undofile
set undodir=~/.vim/undo//
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//

" ---------- Leader ----------
"let mapleader=" "

" ---------- Plugins ----------
call plug#begin('~/.vim/plugged')

Plug 'jiangmiao/auto-pairs'
Plug 'sheerun/vim-polyglot'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'joshdick/onedark.vim'
Plug 'airblade/vim-gitgutter'

call plug#end()

" ---------- Theme ----------
set background=dark
colorscheme onedark

" ---------- Airline ----------
let g:airline_theme='onedark'
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1

" ---------- Auto Pairs ----------
let g:AutoPairsMapCR=1
let g:AutoPairsFlyMode=1
let g:AutoPairsShortcutToggle='<leader>ap'

" ---------- CoC Basic ----------
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

inoremap <silent><expr> <CR>
      \ coc#pum#visible() ? coc#pum#confirm() :
      \ "\<CR>"

function! CheckBackspace() abort
	let col = col('.') - 1
	return !col || getline('.')[col - 1] =~# '\s'
endfunction

" ---------- CoC Navigation ----------
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" ---------- Useful Mappings ----------
inoremap jj <Esc>
inoremap jk <Esc>

nnoremap <leader>h :nohlsearch<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>

" ---------- C / C++ Build & Run ----------
nnoremap <F5> :w<CR>:!cc -Wall -Wextra -Werror % -o %:r && ./%:r<CR>
nnoremap <F6> :w<CR>:!g++ -std=c++17 -Wall -Wextra -Werror % -o %:r && ./%:r<CR>

" ---------- GitGutter ----------
let g:gitgutter_enabled=1

" ---------- Comments Color ----------
highlight Comment ctermfg=245 guifg=#928374
